config/routes.rb
Rails.application.routes.draw do
  # Dashboard Routes
  get "dashboards/index"
  get "/dashboards", to: "dashboards#index"

  # Money Tracker Routes
  resources :money_trackers
  get "/homes", to: "homes#index"

  # Devise Routes
  devise_for :users, skip: [:sessions]
  as :user do
    get 'signin', to: 'devise/sessions#new', as: :new_user_session
    post 'signin', to: 'devise/sessions#create', as: :user_session
    delete 'signout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  # Root Path
  root "dashboards#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/money_tracker.rb
class MoneyTracker < ApplicationRecord
  self.inheritance_column = nil
  belongs_to :user
  validates :amount, numericality: {greater_than: 0}
  validates :transaction_type, inclusion: { in: %w[Income Expense] }
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :money_trackers, dependent: :destroy
  # Include default devise modules. Others available are:

  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index
    end
end

app/controllers/money_trackers_controller.rb
class MoneyTrackersController < ApplicationController
    before_action :authenticate_user!
    def index
        @money_trackers = current_user.money_trackers
    end
    def create
        @income = current_user.money_trackers.new(money_trackers_params)
        @expense = current_user.money_trackers.new(money_trackers_params)
        @available_balance = @income.amount - @expense.amount
    end

    private
    def money_trackers_params
        params.require(:money_tracker).permit(:amount, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/money_trackers_helper.rb
module MoneyTrackersHelper
end

app/views/dashboards/index.html.erb
<h1>Dashboards</h1>
<%= form_for(:user, url: destroy_user_session_path, method: :delete) do |f| %>
    <%= f.submit 'Over&Out' %>
<% end %>

<nav>
  <ul>
    <li><%= link_to "Money Tracker", money_trackers_path %></li>
  </ul>
</nav>

app/views/homes/index.html.erb
<%= link_to 'Sign in', new_user_session_path %>
<%= link_to 'Sign up', new_user_registration_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lifeglow" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>